// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	Add(ctx context.Context, arg AddParams) error
	GetBySlug(ctx context.Context, slug string) (CodeSnippet, error)
	GetPublicSnippets(ctx context.Context) ([]CodeSnippet, error)
	GetRecentPosts(ctx context.Context) ([]CodeSnippet, error)
	UpdateViewCount(ctx context.Context, slug string) error
}

var _ Querier = (*Queries)(nil)
